//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Common.MultiLanguage;
	
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public partial class Screen1 : Neo.ApplicationFramework.Controls.Screen.ScreenWindow, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Screen1()
		{
			this.DataContext = Globals.Instance;
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData()
		{
			System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
			instanceList.Add(this.CreateInstanceData_Default());
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
			aliasInstances.Instances = instanceList.ToArray();
			return aliasInstances;
		}
		
		private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default()
		{
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF AliasInstanceCF1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
			AliasInstanceCF1.Name = "Default";
			AliasInstanceCF1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
			return AliasInstanceCF1;
		}
		
		protected override void BindAliases()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen1));
			this.ApplyResourcesOnWindow();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated)
			{
				return;
			}
			this.ApplyLanguageFont(this.GetCurrentLanguage(), this.FontTemplatesEnabled(), this.GetPropertyBinderFactory());
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
			this.RefreshBindingsOnObjects();
		}
		
		private void RefreshBindingsOnObjects()
		{
		}
	}
}
