//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Tools.Alarm;
	
	
	[System.ComponentModel.DesignerCategory("")]
	public partial class AlarmServer : Neo.ApplicationFramework.Tools.Alarm.AlarmServer, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmGroup m_Default;
		
		private Neo.ApplicationFramework.Tools.Alarm.AlarmItem m_Default_AlarmItem0;
		
		public AlarmServer()
		{
			this.InitializeComponent();
			this.Default_AlarmItem0.AlarmEventInfoRequested += new System.EventHandler<Neo.ApplicationFramework.Interfaces.Events.AlarmEventEventArgs>(this.Default_AlarmItem0_Action_AlarmEventInfoRequested);
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmGroup Default
		{
			get
			{
				return this.m_Default;
			}
			set
			{
				this.m_Default = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Alarm.AlarmItem Default_AlarmItem0
		{
			get
			{
				return this.m_Default_AlarmItem0;
			}
			set
			{
				this.m_Default_AlarmItem0 = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
			this.Default_AlarmItem0.DataBindings.Add(new Neo.ApplicationFramework.Common.Data.DynamicBinding("Value", ((Neo.ApplicationFramework.Common.Data.RealtimeDataItemProxy)(Neo.ApplicationFramework.Common.Data.DataItemProxyFactory.CreateRealtimeProxy("Tags.AlarmBit"))), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never, null));
		}
		
		private void InitializeObjectCreations()
		{
			this.Default = new Neo.ApplicationFramework.Tools.Alarm.AlarmGroup();
			this.Default_AlarmItem0 = new Neo.ApplicationFramework.Tools.Alarm.AlarmItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Default_AlarmItem0)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.Default_AlarmItem0)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.Default.AcknowledgeBackColor = System.Drawing.Color.Green;
			this.Default.AcknowledgeForeColor = System.Drawing.Color.Black;
			this.Default.ActiveBackColor = System.Drawing.Color.Red;
			this.Default.ActiveForeColor = System.Drawing.Color.Black;
			this.Default_AlarmItem0.AcknowledgeRequired = true;
			this.Default_AlarmItem0.ComparerType = Neo.ApplicationFramework.Interfaces.ComparerTypes.NotEqualTo;
			this.Default_AlarmItem0.Contacts = null;
			this.Default_AlarmItem0.DefaultText = "Alarm bit is activated";
			this.Default_AlarmItem0.DisplayName = "AlarmItem0";
			Neo.ApplicationFramework.Common.Dynamics.DynamicString DynamicString1 = new Neo.ApplicationFramework.Common.Dynamics.DynamicString();
			DynamicString1.Text = "Alarm bit is activated";
			this.Default_AlarmItem0.DynamicString = DynamicString1;
			this.Default_AlarmItem0.EnableDistribution = false;
			this.Default_AlarmItem0.GroupId = new System.Guid("6b344737-6f50-4e1d-af07-2f56f755e1c9");
			this.Default_AlarmItem0.GroupName = "Default";
			this.Default_AlarmItem0.History = true;
			this.Default_AlarmItem0.IsDigitalValue = false;
			this.Default_AlarmItem0.Name = "Default_AlarmItem0";
			this.Default_AlarmItem0.OutputDevices = null;
			this.Default_AlarmItem0.RepeatCount = true;
			this.Default_AlarmItem0.TriggerValue = 0;
			this.Default.AlarmItems.Add(this.Default_AlarmItem0);
			this.Default.EnableDistribution = false;
			this.Default.InactiveBackColor = System.Drawing.Color.Yellow;
			this.Default.InactiveForeColor = System.Drawing.Color.Black;
			this.Default.Name = "Default";
			this.Default.NormalBackColor = System.Drawing.SystemColors.Window;
			this.Default.NormalForeColor = System.Drawing.Color.Black;
			this.AlarmGroups.Add(this.Default);
			this.ExternalAlarmDistribution = false;
			this.InternalAlarmDistribution = true;
			this.MaxNumberOfAlarms = 1000;
			this.StorageEvent.AcknowledgeTime = null;
			this.StorageEvent.ActiveTime = null;
			this.StorageEvent.AlarmGroupName = "";
			this.StorageEvent.AlarmGroupText = "";
			this.StorageEvent.AlarmItemId = new System.Guid("00000000-0000-0000-0000-000000000000");
			this.StorageEvent.Count = 0;
			this.StorageEvent.DisplayText = "";
			this.StorageEvent.EnableDistribution = false;
			this.StorageEvent.ForceToList = false;
			this.StorageEvent.History = false;
			this.StorageEvent.InActiveTime = null;
			this.StorageEvent.NormalTime = null;
			this.StorageEvent.RepeatCount = false;
			this.StorageEvent.State = Neo.ApplicationFramework.Interfaces.AlarmState.Normal;
			this.StorageEvent.TableName = "AlarmServer";
			this.StorageEvent.Text = "";
		}
		
		private void Default_AlarmItem0_Action_AlarmEventInfoRequested(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.ScrInfor.Show();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(AlarmServer));
			this.m_Default.Text = resources.GetText("AlarmServer.Default.Text", "Default");
			this.m_Default_AlarmItem0.StaticText = resources.GetText("AlarmServer.Default_AlarmItem0.StaticText", "Alarm bit is activated");
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
		}
	}
}
