//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	[System.ComponentModel.DesignerCategory("")]
	public partial class AuditTrail : Neo.ApplicationFramework.Tools.AuditTrail.AuditTrail, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public AuditTrail()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			// 
			// AuditTrail
			// 
			this.CyclicLogging = false;
			this.MaxSize = 5;
			this.SuppressedLogActionNameList.Add("Acknowledge All Alarms");
			this.SuppressedLogActionNameList.Add("Acknowledge Selected Alarm");
			this.SuppressedLogActionNameList.Add("Acknowledge Visible Alarms");
			this.SuppressedLogActionNameList.Add("Alarm Info");
			this.SuppressedLogActionNameList.Add("Clear All Alarms");
			this.SuppressedLogActionNameList.Add("Clear Visible Alarms");
			this.SuppressedLogActionNameList.Add("Filter Alarms");
			this.SuppressedLogActionNameList.Add("Pause Viewer");
			this.SuppressedLogActionNameList.Add("Toggle IsEnabled State on Selected Alarm");
			this.SuppressedLogActionNameList.Add("Manage Alarms");
			this.SuppressedLogActionNameList.Add("Zoom In Chart");
			this.SuppressedLogActionNameList.Add("Pan Down Chart");
			this.SuppressedLogActionNameList.Add("Pan Left Chart");
			this.SuppressedLogActionNameList.Add("Pan Right Chart");
			this.SuppressedLogActionNameList.Add("Pan Up Chart");
			this.SuppressedLogActionNameList.Add("Reset View In Chart");
			this.SuppressedLogActionNameList.Add("Zoom Out Chart");
			this.SuppressedLogActionNameList.Add("Show Trend Viewer Legend");
			this.SuppressedLogActionNameList.Add("Trend Viewer History");
			this.SuppressedLogActionNameList.Add("Storage Device Detection");
			this.SuppressedLogActionNameList.Add("Show Backlight Settings");
			this.SuppressedLogActionNameList.Add("Set Date and Time");
			this.SuppressedLogActionNameList.Add("Set Time Zone, Region and Daylight Saving");
			this.SuppressedLogActionNameList.Add("Copy Log To Usb Memory");
			this.SuppressedLogActionNameList.Add("Disable Debug Logger");
			this.SuppressedLogActionNameList.Add("Enable Debug Logger");
			this.SuppressedLogActionNameList.Add("Printer Configuration");
			this.SuppressedLogActionNameList.Add("Print Screen");
			this.SuppressedLogActionNameList.Add("Close Application");
			this.SuppressedLogActionNameList.Add("Show Next Screen");
			this.SuppressedLogActionNameList.Add("Show Previous Screen");
			this.SuppressedLogActionNameList.Add("Show Start Screen");
			this.SuppressedLogActionNameList.Add("Back Up Databases");
			this.SuppressedLogActionNameList.Add("Database Export");
			this.SuppressedLogActionNameList.Add("Restore Databases");
			this.SuppressedLogActionNameList.Add("Reset Tag");
			this.SuppressedLogActionNameList.Add("Set String");
			this.SuppressedLogActionNameList.Add("Toggle Tag");
			this.SuppressedLogActionNameList.Add("Open AddressBook");
			this.SuppressedLogActionNameList.Add("Open Routes Configuration");
			this.SuppressedLogActionNameList.Add("Log once");
			this.SuppressedLogActionNameList.Add("Start Logging.");
			this.SuppressedLogActionNameList.Add("Stop Logging.");
			this.SuppressedLogActionNameList.Add("Email Configuration");
			this.SuppressedLogActionNameList.Add("Set Language");
			this.SuppressedLogActionNameList.Add("Change Active Controllers");
			this.SuppressedLogActionNameList.Add("Clear Non Volatile Values");
			this.SuppressedLogActionNameList.Add("Load Recipe");
			this.SuppressedLogActionNameList.Add("End Offline Recipe Editing");
			this.SuppressedLogActionNameList.Add("Export Recipe");
			this.SuppressedLogActionNameList.Add("Import Recipe");
			this.SuppressedLogActionNameList.Add("Start Offline Recipe Editing");
			this.SuppressedLogActionNameList.Add("Generate report");
			this.SuppressedLogActionNameList.Add("Show Screen");
			this.SuppressedLogActionNameList.Add("Close Screen");
			this.SuppressedLogActionNameList.Add("Execute Script");
			this.SuppressedLogActionNameList.Add("Export user accounts");
			this.SuppressedLogActionNameList.Add("Import user accounts");
			this.SuppressedLogActionNameList.Add("Logout");
			this.SuppressedLogActionNameList.Add("Show Users Dialog");
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
		}
		
		private void InitializeBeginInits()
		{
		}
		
		private void InitializeEndInits()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(AuditTrail));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
