//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	[System.ComponentModel.DesignerCategory("")]
	public partial class Controller1 : Neo.ApplicationFramework.Tools.OpcClient.DataSourceContainer, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem1;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem2;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem3;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem4;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem5;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem6;
		
		private Neo.ApplicationFramework.Tools.OpcClient.DataItem DataItem7;
		
		public Controller1()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.DataItem1 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem1", "M0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem2 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem2", "M1", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem3 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem3", "M2", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem4 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem4", "M3", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem5 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem5", "D0", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem6 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem6", "M4", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), false);
			this.DataItem7 = new Neo.ApplicationFramework.Tools.OpcClient.DataItem("DataItem7", "D10", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(32)), 0D, 1D, ((short)(0)), false);
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem1)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem2)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem3)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem4)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem5)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem6)).BeginInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem7)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this.DataItem1)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem2)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem3)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem4)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem5)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem6)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this.DataItem7)).EndInit();
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataItems.Add(this.DataItem1);
			this.DataItems.Add(this.DataItem2);
			this.DataItems.Add(this.DataItem3);
			this.DataItems.Add(this.DataItem4);
			this.DataItems.Add(this.DataItem5);
			this.DataItems.Add(this.DataItem6);
			this.DataItems.Add(this.DataItem7);
			this.Driver = "Demo_Pre2.Demo_Pre2.1";
			this.DriverFormat = Neo.ApplicationFramework.Interfaces.Constants.DriverFormat.MPD;
			this.DriverInitializationString = "";
			this.Node = "";
			this.Servername = "Beijer.InprocessNeo.2";
			this.TargetInfoString = "iXDeveloper;WinXP;Beijer;PC;PC;en;";
			this.Url = "";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Controller1));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
