//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Common.MultiLanguage;
	
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public partial class PC_backg_h1 : Neo.ApplicationFramework.Controls.Screen.ScreenWindow, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public PC_backg_h1()
		{
			this.DataContext = Globals.Instance;
			this.InitializeComponent();
			this.ApplyLanguageInternal();
			this.m_Button.Click += new System.Windows.RoutedEventHandler(this.m_Button_Action_Click);
			this.m_Button1.Click += new System.Windows.RoutedEventHandler(this.m_Button1_Action_Click);
			this.m_Button2.Click += new System.Windows.RoutedEventHandler(this.m_Button2_Action_Click);
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button2);
			}
		}
		
		protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData()
		{
			System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
			instanceList.Add(this.CreateInstanceData_Default());
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
			aliasInstances.Instances = instanceList.ToArray();
			return aliasInstances;
		}
		
		private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default()
		{
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF AliasInstanceCF1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
			AliasInstanceCF1.Name = "Default";
			AliasInstanceCF1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
			return AliasInstanceCF1;
		}
		
		protected override void BindAliases()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(PC_backg_h1));
			this.m_Button.Text = resources.GetText("PC_backg_h1.Button.Text", "Recipe");
			this.m_Button1.Text = resources.GetText("PC_backg_h1.Button1.Text", "User");
			this.m_Button2.Text = resources.GetText("PC_backg_h1.Button2.Text", "Audit Viewer");
			this.ApplyResourcesOnWindow();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated)
			{
				return;
			}
			this.ApplyLanguageFont(this.GetCurrentLanguage(), this.FontTemplatesEnabled(), this.GetPropertyBinderFactory());
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
			this.RefreshBindingsOnObjects();
		}
		
		private void RefreshBindingsOnObjects()
		{
		}
		
		private void m_Button_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Recipe.Show();
		}
		
		private void m_Button1_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Screen_Security.Show();
		}
		
		private void m_Button2_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Audit.Show();
		}
	}
}
