//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	[System.ComponentModel.DesignerCategory("")]
	public partial class Recipe1 : Neo.ApplicationFramework.Tools.Recipe.Recipe, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeL1;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeL2;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeL3;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeL4;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeLSpeed;
		
		private Neo.ApplicationFramework.Tools.Recipe.RecipeItem m_RecipeLInformation;
		
		public Recipe1()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeL1
		{
			get
			{
				return this.m_RecipeL1;
			}
			set
			{
				this.m_RecipeL1 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeL2
		{
			get
			{
				return this.m_RecipeL2;
			}
			set
			{
				this.m_RecipeL2 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeL3
		{
			get
			{
				return this.m_RecipeL3;
			}
			set
			{
				this.m_RecipeL3 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeL4
		{
			get
			{
				return this.m_RecipeL4;
			}
			set
			{
				this.m_RecipeL4 = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeLSpeed
		{
			get
			{
				return this.m_RecipeLSpeed;
			}
			set
			{
				this.m_RecipeLSpeed = value;
			}
		}
		
		public Neo.ApplicationFramework.Tools.Recipe.RecipeItem RecipeLInformation
		{
			get
			{
				return this.m_RecipeLInformation;
			}
			set
			{
				this.m_RecipeLInformation = value;
			}
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.RecipeL1 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeL2 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeL3 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeL4 = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeLSpeed = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
			this.RecipeLInformation = new Neo.ApplicationFramework.Tools.Recipe.RecipeItem();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.DataVersion = ((long)(5));
			this.FieldNames.Add("Full Speed");
			this.Guid = new System.Guid("89eb1049-04c8-4a48-ad12-493198a48527");
			this.RecipeL1.ColumnName = "RecipeL1";
			this.RecipeL1.DataConnection = "Tags.RecipeL1";
			this.RecipeL1.Name = "RecipeL1";
			this.RecipeL1.VisualSortOrder = 99;
			this.RecipeL2.ColumnName = "RecipeL2";
			this.RecipeL2.DataConnection = "Tags.RecipeL2";
			this.RecipeL2.Name = "RecipeL2";
			this.RecipeL2.VisualSortOrder = 100;
			this.RecipeL3.ColumnName = "RecipeL3";
			this.RecipeL3.DataConnection = "Tags.RecipeL3";
			this.RecipeL3.Name = "RecipeL3";
			this.RecipeL3.VisualSortOrder = 101;
			this.RecipeL4.ColumnName = "RecipeL4";
			this.RecipeL4.DataConnection = "Tags.RecipeL4";
			this.RecipeL4.Name = "RecipeL4";
			this.RecipeL4.VisualSortOrder = 102;
			this.RecipeLSpeed.ColumnName = "RecipeLSpeed";
			this.RecipeLSpeed.DataConnection = "Tags.RecipeLSpeed";
			this.RecipeLSpeed.Name = "RecipeLSpeed";
			this.RecipeLSpeed.VisualSortOrder = 103;
			this.RecipeLInformation.ColumnName = "RecipeLInformation";
			this.RecipeLInformation.DataConnection = "Tags.RecipeInfo";
			this.RecipeLInformation.Name = "RecipeLInformation";
			this.RecipeLInformation.VisualSortOrder = 104;
			this.RecipeItems.Add(this.RecipeL1);
			this.RecipeItems.Add(this.RecipeL2);
			this.RecipeItems.Add(this.RecipeL3);
			this.RecipeItems.Add(this.RecipeL4);
			this.RecipeItems.Add(this.RecipeLSpeed);
			this.RecipeItems.Add(this.RecipeLInformation);
			this.SchemaVersion = ((long)(41));
			this.TableName = "Recipe1";
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Recipe1));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
}
