//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Common.MultiLanguage;
	
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public partial class Recipe : Neo.ApplicationFramework.Controls.Screen.ScreenWindow, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Recipe()
		{
			this.DataContext = Globals.Instance;
			this.InitializeComponent();
			this.ApplyLanguageInternal();
			this.m_Switch08.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_Switch08_Action_MouseDown);
			this.m_MultiPicture1.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_MultiPicture1_Action_MouseDown);
			this.m_MultiPicture2.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_MultiPicture2_Action_MouseDown);
			this.m_MultiPicture3.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_MultiPicture3_Action_MouseDown);
			this.m_Button27.Click += new System.Windows.RoutedEventHandler(this.m_Button27_Action_Click);
			this.m_Button28.Click += new System.Windows.RoutedEventHandler(this.m_Button28_Action_Click);
			this.m_Button7.Click += new System.Windows.RoutedEventHandler(this.m_Button7_Action_Click);
			this.m_Button6.Click += new System.Windows.RoutedEventHandler(this.m_Button6_Action_Click);
			this.m_Button26.Click += new System.Windows.RoutedEventHandler(this.m_Button26_Action_Click);
		}
		
		protected Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter AnalogNumeric1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter>(this.m_AnalogNumeric1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter Switch08
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_Switch08);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.MeterAdapter Slider1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.MeterAdapter>(this.m_Slider1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter AnalogNumeric2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter>(this.m_AnalogNumeric2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text4
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text4);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter AnalogNumeric3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.AnalogNumericAdapter>(this.m_AnalogNumeric3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text6
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text6);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text5
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text5);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text7
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text7);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button27
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button27);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button28
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button28);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button7
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button7);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button6
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button6);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button26
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button26);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl4
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl4);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ColorElementAdapter DigitalClock1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ColorElementAdapter>(this.m_DigitalClock1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture7
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture7);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture8
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture8);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture9
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture9);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture10
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture10);
			}
		}
		
		protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData()
		{
			System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
			instanceList.Add(this.CreateInstanceData_Default());
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
			aliasInstances.Instances = instanceList.ToArray();
			return aliasInstances;
		}
		
		private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default()
		{
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF AliasInstanceCF1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
			AliasInstanceCF1.Name = "Default";
			AliasInstanceCF1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
			return AliasInstanceCF1;
		}
		
		protected override void BindAliases()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Recipe));
			this.m_AnalogNumeric1.Prefix = resources.GetText("Recipe.AnalogNumeric1.Prefix", "Current Settings:    ");
			this.m_Text2.Text = resources.GetText("Recipe.Text2.Text", "OFFLINE EDIT");
			this.m_Text3.Text = resources.GetText("Recipe.Text3.Text", "Information");
			this.m_Text4.Text = resources.GetText("Recipe.Text4.Text", "Setpoint Speed  %");
			this.m_Text6.Text = resources.GetText("Recipe.Text6.Text", "Machine Settings");
			this.m_Text5.Text = resources.GetText("Recipe.Text5.Text", "Offline Editing");
			this.m_Text7.Text = resources.GetText("Recipe.Text7.Text", "Recipe Actions");
			this.m_Button27.Text = resources.GetText("Recipe.Button27.Text", "Save");
			this.m_Button28.Text = resources.GetText("Recipe.Button28.Text", "Load");
			this.m_Button7.Text = resources.GetText("Recipe.Button7.Text", "Delete");
			this.m_Button6.Text = resources.GetText("Recipe.Button6.Text", "Exit");
			this.m_Button26.Text = resources.GetText("Recipe.Button26.Text", "Edit");
			this.m_Text1.Text = resources.GetText("Recipe.Text1.Text", "Recipe Management");
			this.ApplyResourcesOnWindow();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated)
			{
				return;
			}
			this.ApplyLanguageFont(this.GetCurrentLanguage(), this.FontTemplatesEnabled(), this.GetPropertyBinderFactory());
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
			this.RefreshBindingsOnObjects();
		}
		
		private void RefreshBindingsOnObjects()
		{
		}
		
		private void m_Switch08_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.RecipeL1.ToggleTag();
		}
		
		private void m_MultiPicture1_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.RecipeL2.ToggleTag();
		}
		
		private void m_MultiPicture2_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.RecipeL3.ToggleTag();
		}
		
		private void m_MultiPicture3_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.RecipeL4.ToggleTag();
		}
		
		private void m_Button27_Action_Click(object sender, System.EventArgs e)
		{
			string recipeFieldName = Neo.ApplicationFramework.Generated.Globals.Recipe1.ShowSelectRecipeDialog(Neo.ApplicationFramework.Interfaces.DialogKind.Save);
			if (string.IsNullOrEmpty(recipeFieldName))
			{
				return;
			}
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button27", "Click", "Save Recipe", "Recipe1", recipeFieldName, "");
			Neo.ApplicationFramework.Generated.Globals.Recipe1.SaveRecipe(recipeFieldName);
		}
		
		private void m_Button28_Action_Click(object sender, System.EventArgs e)
		{
			string recipeFieldName = Neo.ApplicationFramework.Generated.Globals.Recipe1.ShowSelectRecipeDialog(Neo.ApplicationFramework.Interfaces.DialogKind.Load);
			if (string.IsNullOrEmpty(recipeFieldName))
			{
				return;
			}
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button28", "Click", "Load Recipe", "Recipe1", recipeFieldName, "");
			Neo.ApplicationFramework.Generated.Globals.Recipe1.LoadRecipe(recipeFieldName);
		}
		
		private void m_Button7_Action_Click(object sender, System.EventArgs e)
		{
			string recipeFieldName = Neo.ApplicationFramework.Generated.Globals.Recipe1.ShowSelectRecipeDialog(Neo.ApplicationFramework.Interfaces.DialogKind.Delete);
			if (string.IsNullOrEmpty(recipeFieldName))
			{
				return;
			}
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button7", "Click", "Delete Recipe", "Recipe1", recipeFieldName, "");
			Neo.ApplicationFramework.Generated.Globals.Recipe1.DeleteRecipe(recipeFieldName);
		}
		
		private void m_Button6_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.RecipeOffline.ResetTag();
			Neo.ApplicationFramework.Generated.Globals.Recipe1.EndOfflineRecipeEditing();
		}
		
		private void m_Button26_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.RecipeOffline.SetTag();
			Neo.ApplicationFramework.Generated.Globals.Recipe1.StartOfflineRecipeEditing();
		}
	}
}
