//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	using Neo.ApplicationFramework.Common.MultiLanguage;
	
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public partial class Screen_Security : Neo.ApplicationFramework.Controls.Screen.ScreenWindow, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Screen_Security()
		{
			this.DataContext = Globals.Instance;
			this.InitializeComponent();
			this.ApplyLanguageInternal();
			this.m_MultiPicture2.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_MultiPicture2_Action_MouseDown);
			this.m_MultiPicture3.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_MultiPicture3_Action_MouseDown);
			this.m_MultiPicture4.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_MultiPicture4_Action_MouseDown);
			this.m_MultiPicture5.MouseDown += new System.Windows.Input.MouseButtonEventHandler(this.m_MultiPicture5_Action_MouseDown);
			this.m_Button19.Click += new System.Windows.RoutedEventHandler(this.m_Button19_Action_Click);
			this.m_Button15.Click += new System.Windows.RoutedEventHandler(this.m_Button15_Action_Click);
			this.m_Button3.Click += new System.Windows.RoutedEventHandler(this.m_Button3_Action_Click);
			this.m_Button16.Click += new System.Windows.RoutedEventHandler(this.m_Button16_Action_Click);
			this.m_Button.Click += new System.Windows.RoutedEventHandler(this.m_Button_Action_Click);
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text7
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text7);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ColorElementAdapter DigitalClock1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ColorElementAdapter>(this.m_DigitalClock1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox6
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox6);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox12
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox12);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox13
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox13);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox10
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox10);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox21
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox21);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox16
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox16);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox17
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox17);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox19
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox19);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox20
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox20);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolViewbox22
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolViewbox22);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.MeterAdapter LinearMeter1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.MeterAdapter>(this.m_LinearMeter1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.MeterAdapter LinearMeter2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.MeterAdapter>(this.m_LinearMeter2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text6
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text6);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text4
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text4);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text5
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text5);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text12
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text12);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture2
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture2);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture4
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture4);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ElementAdapter MultiPicture5
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ElementAdapter>(this.m_MultiPicture5);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text17
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text17);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl6
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl6);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text18
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text18);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text19
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text19);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text8
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text8);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.TextElementAdapter Text9
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.TextElementAdapter>(this.m_Text9);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.RenderableAdapter SymbolControl1
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.RenderableAdapter>(this.m_SymbolControl1);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button19
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button19);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button15
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button15);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button3
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button3);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button16
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button16);
			}
		}
		
		protected Neo.ApplicationFramework.Controls.Script.ButtonAdapter Button
		{
			get
			{
				return this.AdapterService.CreateAdapter<Neo.ApplicationFramework.Controls.Script.ButtonAdapter>(this.m_Button);
			}
		}
		
		protected override Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF CreateInstanceData()
		{
			System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF> instanceList = new System.Collections.Generic.List<Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF>(1);
			instanceList.Add(this.CreateInstanceData_Default());
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF aliasInstances = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstancesCF();
			aliasInstances.Instances = instanceList.ToArray();
			return aliasInstances;
		}
		
		private Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF CreateInstanceData_Default()
		{
			Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF AliasInstanceCF1 = new Neo.ApplicationFramework.Common.Alias.Entities.AliasInstanceCF();
			AliasInstanceCF1.Name = "Default";
			AliasInstanceCF1.Values = new Neo.ApplicationFramework.Common.Alias.Entities.AliasValueCF[0];
			return AliasInstanceCF1;
		}
		
		protected override void BindAliases()
		{
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Screen_Security));
			this.m_Text7.Text = resources.GetText("Screen_Security.Text7.Text", "Security Management");
			this.m_Text6.Text = resources.GetText("Screen_Security.Text6.Text", "V313");
			this.m_Text3.Text = resources.GetText("Screen_Security.Text3.Text", "V314");
			this.m_Text4.Text = resources.GetText("Screen_Security.Text4.Text", "Tank 1");
			this.m_Text5.Text = resources.GetText("Screen_Security.Text5.Text", "V315");
			this.m_Text1.Text = resources.GetText("Screen_Security.Text1.Text", "V316\r\nV316");
			this.m_Text12.Text = resources.GetText("Screen_Security.Text12.Text", "Tank 2");
			this.m_Text17.Text = resources.GetText("Screen_Security.Text17.Text", "UserName: user\r\nPassword:  user\r\n\r\nUserName: advuser\r\nPassword:  advuser\r\n\r\nUserN" +
					"ame: admin\r\nPassword:  admin\r\n");
			this.m_Text18.Text = resources.GetText("Screen_Security.Text18.Text", "(authorized to change V313 and V314) \r\n\r\n\r\n(authorized to change V315 and V316)  " +
					"\r\n\r\n\r\n(adminstrator rights including authorization\r\n to import/export users)");
			this.m_Text19.Text = resources.GetText("Screen_Security.Text19.Text", "User information and user groups:");
			this.m_Text8.Text = resources.GetText("Screen_Security.Text8.Text", "User Administration:");
			this.m_Text9.Text = resources.GetText("Screen_Security.Text9.Text", "Clicking the \"Import\" button allows you to import the user database from a USB me" +
					"mory stick.\r\nClicking the \"Export\" button allows you to export the user database" +
					" to a USB memory stick.\r\n");
			this.m_Button19.Text = resources.GetText("Screen_Security.Button19.Text", "Import");
			this.m_Button15.Text = resources.GetText("Screen_Security.Button15.Text", "Logout");
			this.m_Button3.Text = resources.GetText("Screen_Security.Button3.Text", "Login");
			this.m_Button16.Text = resources.GetText("Screen_Security.Button16.Text", "Export");
			this.m_Button.Text = resources.GetText("Screen_Security.Button.Text", "Back");
			this.ApplyResourcesOnWindow();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected override void ApplyLanguage()
		{
			if (((Neo.ApplicationFramework.Interfaces.IScreen)(this)).IsCachedDeactivated)
			{
				return;
			}
			this.ApplyLanguageFont(this.GetCurrentLanguage(), this.FontTemplatesEnabled(), this.GetPropertyBinderFactory());
			this.ApplyLanguageInternal();
			base.ApplyLanguage();
			this.RefreshBindingsOnObjects();
		}
		
		private void RefreshBindingsOnObjects()
		{
		}
		
		private void m_MultiPicture2_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.valve313.ToggleTag();
		}
		
		private void m_MultiPicture3_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.valve314.ToggleTag();
		}
		
		private void m_MultiPicture4_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.valve315.ToggleTag();
		}
		
		private void m_MultiPicture5_Action_MouseDown(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Tags.valve316.ToggleTag();
		}
		
		private void m_Button19_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Security.ImportUsers();
		}
		
		private void m_Button15_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Security.Logout();
		}
		
		private void m_Button3_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.AuditTrailService.LogAction("m_Button3", "Click", "Login", "Security", "");
			Neo.ApplicationFramework.Generated.Globals.Security.Login();
		}
		
		private void m_Button16_Action_Click(object sender, System.EventArgs e)
		{
			Neo.ApplicationFramework.Generated.Globals.Security.ExportUsers();
		}
		
		private void m_Button_Action_Click(object sender, System.EventArgs e)
		{
			Core.Api.Service.ServiceContainerCF.GetService<Neo.ApplicationFramework.Interfaces.IScreenManager>().ActionBackScreen();
		}
	}
}
