//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neo.ApplicationFramework.Generated
{
	using Neo.ApplicationFramework.Tools.Actions;
	
	
	[System.ComponentModel.DesignerCategory("")]
	public partial class Tags : Neo.ApplicationFramework.Tools.OpcClient.GlobalController, Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage
	{
		
		public Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem SystemTagLatestLoadedRecipeName;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RecipeL1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RecipeL2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RecipeL3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RecipeL4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RecipeLSpeed;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RecipeOffline;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag RecipeInfo;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Counter0;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Counter2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag valve313;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag valve314;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag valve315;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag valve316;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Temp;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem btStart;
		
		public Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem btStop;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag AlarmBit;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_CurrentNumber;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_StartTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_EndTime;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_IsActive;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_TotalQty;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_RejectedQty;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_ReportReady;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_TotalAlarms;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_CriticalAlarms;
		
		public Neo.ApplicationFramework.Tools.OpcClient.LightweightTag Batch_WarningAlarms;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup1;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup2;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup3;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup4;
		
		public Neo.ApplicationFramework.Tools.OpcClient.PollGroup PollGroup5;
		
		public Tags()
		{
			this.InitializeComponent();
			this.ApplyLanguageInternal();
		}
		
		private void InitializeComponent()
		{
			this.InitializeObjectCreations();
			this.InitializeBeginInits();
			this.InitializeObjects();
			this.InitializeEndInits();
			this.ConnectDataBindings();
		}
		
		protected override void Dispose(bool disposing)
		{
			base.Dispose(disposing);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		public virtual void ConnectDataBindings()
		{
		}
		
		private void InitializeObjectCreations()
		{
			this.SystemTagLatestLoadedRecipeName = new Neo.ApplicationFramework.Tools.OpcClient.SystemDataItem("Latest Loaded Recipe Name", "SystemTagLatestLoadedRecipeName", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), ((short)(100)), 0D, 1D, ((short)(0)), false, "Value Change", Core.Api.DataSource.AccessRights.Read, "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "Name of the latest loaded recipe", ((short)(1)), "", "");
			this.RecipeL1 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RecipeL1", "Controller1.DataItem1", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), true, "", null);
			this.RecipeL2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RecipeL2", "Controller1.DataItem2", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), true, "", null);
			this.RecipeL3 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RecipeL3", "Controller1.DataItem3", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), true, "", null);
			this.RecipeL4 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RecipeL4", "Controller1.DataItem4", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), true, "", null);
			this.RecipeLSpeed = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RecipeLSpeed", "Controller1.DataItem5", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), true, "", null);
			this.RecipeOffline = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RecipeOffline", "Controller1.DataItem6", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), true, "", null);
			this.RecipeInfo = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("RecipeInfo", "Controller1.DataItem7", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), true, "", null);
			this.Counter0 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Counter0", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Counter2 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Counter2", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.valve313 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("valve313", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.valve314 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("valve314", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.valve315 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("valve315", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.valve316 = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("valve316", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), false, "", null);
			this.Temp = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Temp", "Controller1.DataItem8", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_REAL4)), false, "", null);
			this.btStart = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("btStart", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), true, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.btStop = new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataItem("btStop", ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), ((short)(1)), 0D, 1D, ((short)(0)), true, "Value Change", ((Core.Api.DataSource.AccessRights)((Core.Api.DataSource.AccessRights.Read | Core.Api.DataSource.AccessRights.Write))), "PollGroup1", false, false, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DEFAULT)), "", ((short)(1)), "", "");
			this.AlarmBit = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("AlarmBit", "Controller1.DataItem11", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "", null);
			this.Batch_CurrentNumber = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_CurrentNumber", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_STRING)), false, "Current batch number", null);
			this.Batch_StartTime = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_StartTime", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DATETIME)), false, "Batch start time", null);
			this.Batch_EndTime = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_EndTime", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_DATETIME)), false, "Batch end time", null);
			this.Batch_IsActive = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_IsActive", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "Batch is active", null);
			this.Batch_TotalQty = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_TotalQty", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), false, "Total quantity", null);
			this.Batch_RejectedQty = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_RejectedQty", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER4)), false, "Rejected quantity", null);
			this.Batch_ReportReady = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_ReportReady", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_BIT)), false, "Report ready", null);
			this.Batch_TotalAlarms = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_TotalAlarms", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "Total alarms", null);
			this.Batch_CriticalAlarms = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_CriticalAlarms", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "Critical count", null);
			this.Batch_WarningAlarms = new Neo.ApplicationFramework.Tools.OpcClient.LightweightTag("Batch_WarningAlarms", "", 500, ((Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE)(Neo.ApplicationFramework.Interop.DataSource.BEDATATYPE.DT_INTEGER2)), false, "Warning count", null);
			this.PollGroup1 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup2 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup3 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup4 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
			this.PollGroup5 = new Neo.ApplicationFramework.Tools.OpcClient.PollGroup();
		}
		
		private void InitializeBeginInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
		}
		
		private void InitializeEndInits()
		{
			((System.ComponentModel.ISupportInitialize)(this)).EndInit();
		}
		
		private void InitializeObjects()
		{
			this.SystemTagLatestLoadedRecipeName.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[0], new string[0], true));
			this.SystemTagLatestLoadedRecipeName.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 1, new string[0], new string[0], true));
			this.btStart.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller1"}, new string[] {
							"DataItem9"}, true));
			this.btStop.GlobalDataSubItems.Add(new Neo.ApplicationFramework.Tools.OpcClient.GlobalDataSubItem(null, 0, new string[] {
							"Controller1"}, new string[] {
							"DataItem10"}, true));
			this.GlobalDataItems.Add(this.SystemTagLatestLoadedRecipeName);
			this.LightweightTags.Add(this.RecipeL1);
			this.LightweightTags.Add(this.RecipeL2);
			this.LightweightTags.Add(this.RecipeL3);
			this.LightweightTags.Add(this.RecipeL4);
			this.LightweightTags.Add(this.RecipeLSpeed);
			this.LightweightTags.Add(this.RecipeOffline);
			this.LightweightTags.Add(this.RecipeInfo);
			this.LightweightTags.Add(this.Counter0);
			this.LightweightTags.Add(this.Counter2);
			this.LightweightTags.Add(this.valve313);
			this.LightweightTags.Add(this.valve314);
			this.LightweightTags.Add(this.valve315);
			this.LightweightTags.Add(this.valve316);
			this.LightweightTags.Add(this.Temp);
			this.GlobalDataItems.Add(this.btStart);
			this.GlobalDataItems.Add(this.btStop);
			this.LightweightTags.Add(this.AlarmBit);
			this.LightweightTags.Add(this.Batch_CurrentNumber);
			this.LightweightTags.Add(this.Batch_StartTime);
			this.LightweightTags.Add(this.Batch_EndTime);
			this.LightweightTags.Add(this.Batch_IsActive);
			this.LightweightTags.Add(this.Batch_TotalQty);
			this.LightweightTags.Add(this.Batch_RejectedQty);
			this.LightweightTags.Add(this.Batch_ReportReady);
			this.LightweightTags.Add(this.Batch_TotalAlarms);
			this.LightweightTags.Add(this.Batch_CriticalAlarms);
			this.LightweightTags.Add(this.Batch_WarningAlarms);
			this.PollGroup1.Interval = 500;
			this.PollGroup1.Name = "PollGroup1";
			this.PollGroup2.Interval = 500;
			this.PollGroup2.Name = "PollGroup2";
			this.PollGroup3.Interval = 500;
			this.PollGroup3.Name = "PollGroup3";
			this.PollGroup4.Interval = 500;
			this.PollGroup4.Name = "PollGroup4";
			this.PollGroup5.Interval = 500;
			this.PollGroup5.Name = "PollGroup5";
			this.PollGroups.Add(this.PollGroup1);
			this.PollGroups.Add(this.PollGroup2);
			this.PollGroups.Add(this.PollGroup3);
			this.PollGroups.Add(this.PollGroup4);
			this.PollGroups.Add(this.PollGroup5);
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		private void ApplyLanguageInternal()
		{
			Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager resources = new Neo.ApplicationFramework.Tools.MultiLanguage.MultiLanguageResourceManager(typeof(Tags));
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		void Neo.ApplicationFramework.Interfaces.ISupportMultiLanguage.ApplyLanguage()
		{
			this.ApplyLanguage();
		}
		
		[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
		protected virtual void ApplyLanguage()
		{
			this.ApplyLanguageInternal();
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForRecipeL1 : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			if ((value == 0D))
			{
				return "RecipeL1 Disable";
			}
			if ((value == 1D))
			{
				return "RecipeL1 Enable";
			}
			return string.Empty;
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForRecipeL2 : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			if ((value == 0D))
			{
				return "RecipeL2 Disable";
			}
			if ((value == 1D))
			{
				return "RecipeL2 Enable";
			}
			return string.Empty;
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForRecipeL3 : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			if ((value == 0D))
			{
				return "RecipeL3 Disable";
			}
			if ((value == 1D))
			{
				return "RecipeL3 Enable";
			}
			return string.Empty;
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForRecipeL4 : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			if ((value == 0D))
			{
				return "RecipeL4 Disable";
			}
			if ((value == 1D))
			{
				return "RecipeL4 Enable";
			}
			return string.Empty;
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForRecipeLSpeed : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			return "RecipeLSpeed_Change Value";
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForTemp : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			return "Comment";
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForbtStart : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			if ((value == 0D))
			{
				return "Button Start None Actived";
			}
			if ((value == 1D))
			{
				return "Button Start Actived";
			}
			return string.Empty;
		}
	}
	
	[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
	public class AuditTrailDescriptionsForbtStop : Neo.ApplicationFramework.Interfaces.IAuditTrailDescriptions
	{
		
		public string GetDescription(double value)
		{
			if ((value == 0D))
			{
				return "Button Stop None Actived";
			}
			if ((value == 1D))
			{
				return "Button Stop Actived";
			}
			return string.Empty;
		}
	}
}
